server:
  port: 80
  salt: rapid
  // environment of server: [ debug, production ]
  env: debug
  base: http://rapid.cotr.me/
  api: http://rapid.cotr.me/api/
  demoAppKey: 88587CD267E00E016B545E38FD133FCA077535F9B91C0E246FCD48AA5C77996DC935833C27C9A0EC0888D15ACD941C0B461716F61EAC6B7410BB9C46642B0808BF4C32E261A40F385070B87F9CBCE3B51B20E83A8D11B08D
database:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: ""
  db: rapid
site:
  front: Rap-ID
  demo: Rap-Identity
log:
  level: error
content:
  front:
    banner: Rapid Automated Protocol - IDentity
  demo:
    banner: e-ID System Based on Rap-ID
