server:
  port: 80
database:
  ip: 127.0.0.1
  port: 3306
  user: root
  pass: ""
site:
  front: Rap-ID
  demo: Rap支付
log:
  level: error
content:
  front:
    banner: 快速安全实名认证算法
  demo:
    banner: Rap-ID支付演示
